import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static String FROM = "From:";
    public static String SUBJECT = "Subject:";
    public static String DATE = "Date:";

    public static void main(String[] args) {
	// Still need to de-tar/gz sampleEmails.tar.gz to a dir
        App app = new App("/MYD/RES/RESMARKRW/GITCLONE/validityHW/sampleEmails");
        app.iterateOverFiles();
    }

    private String rootPath;


    App() {

    }

    App(String rootPath) {
        setRootPath(rootPath);
    }


    public void iterateOverFiles() {
        File f = new File(getRootPath());
        BufferedReader br = null;

        File[] files = f.listFiles();

        for(File file : files) {

            if(file.isFile()) {
                try {
//                    System.out.println(file.getAbsolutePath());
                    br = new BufferedReader(new FileReader(file));
                    System.out.println(file.getAbsolutePath() + "|" + processFile(br));
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
                finally {
                    if(br != null) {
                        try {
                            br.close();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }
                }
            }
        }
    }

    public String processFile(BufferedReader input) {

        String from = "", subject = "", date = "";

        Pattern fromPattern = Pattern.compile("From: .*<(.*)>");
        Pattern subjectPattern = Pattern.compile("Subject: (.*)");
        Pattern datePattern = Pattern.compile("Date: (.*)");

        try {
            String line;

            while((line = input.readLine()) != null) {

                Matcher m = fromPattern.matcher(line);
                if(m.find()) {
                    from = m.group(1);
                }
                m = subjectPattern.matcher(line);
                if(m.find()) {
                    subject = m.group(1);
                }
                m = datePattern.matcher(line);
                if(m.find()) {
                    date = m.group(1);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return String.format("%s|%s|%s", from, subject, date);
    }


    public String getRootPath() {
        return rootPath;
    }

    public void setRootPath(String rootPath) {
        this.rootPath = rootPath;
    }
}
