/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.InputStreamReader;

import static org.junit.Assert.assertEquals;

public class AppTest {

    @Test public void fromOnly() {
        App classUnderTest = new App();
        String content = "From: test<test@test.com>\n";
        BufferedReader reader = new BufferedReader(new InputStreamReader(new ByteArrayInputStream(content.getBytes())));

        assertEquals("test@test.com||", classUnderTest.processFile(reader));
    }

    @Test public void allFields() {
        App classUnderTest = new App();
        String content = "From: test<test@test.com>\nSubject: Test Subject\nDate: 11/17/2019\n";
        BufferedReader reader = new BufferedReader(new InputStreamReader(new ByteArrayInputStream(content.getBytes())));

        assertEquals("test@test.com|Test Subject|11/17/2019", classUnderTest.processFile(reader));
    }
}
